include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - document_ignores
    - invalid_runtime_check_with_js_interop_types
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - unintended_html_in_doc_comment
    - unnecessary_await_in_return
    - unnecessary_breaks
