name: work_j832_com
description: kevmoo @ Work blog migrated to Dart and Jaspr
publish_to: none

environment:
  sdk: ^3.12.0-0

dependencies:
  jaspr: ^0.23.1
  jaspr_router: ^0.8.2
  markdown: ^7.3.0
  path: ^1.9.0
  universal_web: ^1.1.1
  xml: ^7.0.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.19
  checks: ^0.3.0
  dart_flutter_team_lints: ^3.0.0
  http: ^1.2.0
  jaspr_builder: ^0.23.1
  test: ^1.25.0
jaspr:
  mode: static
