title: "Flutter, Dart, AND WASM-GC: A New Model for Web Applications"
subTitle: "Wasm I/O"
uri: "https://www.youtube.com/watch?v=Nkjc9r0WDNo"
date: 2023-03-23
flavor: youtube
tags:
  - Flutter
  - Dart
  - wasm
  - web
